"""Add game_user Association Table

Revision ID: 4fe0fdea4953
Revises: 38f60e0eede5
Create Date: 2023-08-31 21:25:26.211011

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4fe0fdea4953'
down_revision = '38f60e0eede5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
